[tool.poetry]
name = "automation"
version = "0.1.0"
description = ""
authors = ["Josh Devins <hi@joshdevins.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
